version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://database:5432/rest-api
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    ports:
      - "8080:8080"

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: rest-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./scripts/.:/docker-entrypoint-initdb.d/.

volumes:
  scripts: